//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Client1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPersonalData", ReplyAction="*")]
        Project_Client1.ServiceReference1.AddPersonalDataResponse AddPersonalData(Project_Client1.ServiceReference1.AddPersonalDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPersonalData", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddPersonalDataResponse> AddPersonalDataAsync(Project_Client1.ServiceReference1.AddPersonalDataRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAppointment", ReplyAction="*")]
        Project_Client1.ServiceReference1.AddAppointmentResponse AddAppointment(Project_Client1.ServiceReference1.AddAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddAppointmentResponse> AddAppointmentAsync(Project_Client1.ServiceReference1.AddAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name description from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddReviews", ReplyAction="*")]
        Project_Client1.ServiceReference1.AddReviewsResponse AddReviews(Project_Client1.ServiceReference1.AddReviewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddReviews", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddReviewsResponse> AddReviewsAsync(Project_Client1.ServiceReference1.AddReviewsRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePersonalData", ReplyAction="*")]
        Project_Client1.ServiceReference1.DeletePersonalDataResponse DeletePersonalData(Project_Client1.ServiceReference1.DeletePersonalDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePersonalData", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.DeletePersonalDataResponse> DeletePersonalDataAsync(Project_Client1.ServiceReference1.DeletePersonalDataRequest request);
        
        // CODEGEN: Generating message contract since element name id_p from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAppointment", ReplyAction="*")]
        Project_Client1.ServiceReference1.DeleteAppointmentResponse DeleteAppointment(Project_Client1.ServiceReference1.DeleteAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.DeleteAppointmentResponse> DeleteAppointmentAsync(Project_Client1.ServiceReference1.DeleteAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeAppointment", ReplyAction="*")]
        Project_Client1.ServiceReference1.ChangeAppointmentResponse ChangeAppointment(Project_Client1.ServiceReference1.ChangeAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangeAppointmentResponse> ChangeAppointmentAsync(Project_Client1.ServiceReference1.ChangeAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePersonalData", ReplyAction="*")]
        Project_Client1.ServiceReference1.ChangePersonalDataResponse ChangePersonalData(Project_Client1.ServiceReference1.ChangePersonalDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePersonalData", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangePersonalDataResponse> ChangePersonalDataAsync(Project_Client1.ServiceReference1.ChangePersonalDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReview", ReplyAction="*")]
        void DeleteReview(int id_r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReview", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteReviewAsync(int id_r);
        
        // CODEGEN: Generating message contract since element name description from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeReview", ReplyAction="*")]
        Project_Client1.ServiceReference1.ChangeReviewResponse ChangeReview(Project_Client1.ServiceReference1.ChangeReviewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeReview", ReplyAction="*")]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangeReviewResponse> ChangeReviewAsync(Project_Client1.ServiceReference1.ChangeReviewRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonalDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersonalData", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.AddPersonalDataRequestBody Body;
        
        public AddPersonalDataRequest() {
        }
        
        public AddPersonalDataRequest(Project_Client1.ServiceReference1.AddPersonalDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPersonalDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phoneNo;
        
        public AddPersonalDataRequestBody() {
        }
        
        public AddPersonalDataRequestBody(string cnp, string name, string surname, string age, string phoneNo) {
            this.cnp = cnp;
            this.name = name;
            this.surname = surname;
            this.age = age;
            this.phoneNo = phoneNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonalDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersonalDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.AddPersonalDataResponseBody Body;
        
        public AddPersonalDataResponse() {
        }
        
        public AddPersonalDataResponse(Project_Client1.ServiceReference1.AddPersonalDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPersonalDataResponseBody {
        
        public AddPersonalDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAppointment", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.AddAppointmentRequestBody Body;
        
        public AddAppointmentRequest() {
        }
        
        public AddAppointmentRequest(Project_Client1.ServiceReference1.AddAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_a;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hour;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string instructor;
        
        public AddAppointmentRequestBody() {
        }
        
        public AddAppointmentRequestBody(int id_a, string cnp, string date, string hour, string instructor) {
            this.id_a = id_a;
            this.cnp = cnp;
            this.date = date;
            this.hour = hour;
            this.instructor = instructor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.AddAppointmentResponseBody Body;
        
        public AddAppointmentResponse() {
        }
        
        public AddAppointmentResponse(Project_Client1.ServiceReference1.AddAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddAppointmentResponseBody {
        
        public AddAppointmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddReviewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddReviews", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.AddReviewsRequestBody Body;
        
        public AddReviewsRequest() {
        }
        
        public AddReviewsRequest(Project_Client1.ServiceReference1.AddReviewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddReviewsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_r;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char stars;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        public AddReviewsRequestBody() {
        }
        
        public AddReviewsRequestBody(int id_r, int id_a, char stars, string description) {
            this.id_r = id_r;
            this.id_a = id_a;
            this.stars = stars;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddReviewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddReviewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.AddReviewsResponseBody Body;
        
        public AddReviewsResponse() {
        }
        
        public AddReviewsResponse(Project_Client1.ServiceReference1.AddReviewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddReviewsResponseBody {
        
        public AddReviewsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePersonalDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePersonalData", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.DeletePersonalDataRequestBody Body;
        
        public DeletePersonalDataRequest() {
        }
        
        public DeletePersonalDataRequest(Project_Client1.ServiceReference1.DeletePersonalDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePersonalDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        public DeletePersonalDataRequestBody() {
        }
        
        public DeletePersonalDataRequestBody(string cnp) {
            this.cnp = cnp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePersonalDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePersonalDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.DeletePersonalDataResponseBody Body;
        
        public DeletePersonalDataResponse() {
        }
        
        public DeletePersonalDataResponse(Project_Client1.ServiceReference1.DeletePersonalDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeletePersonalDataResponseBody {
        
        public DeletePersonalDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAppointment", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.DeleteAppointmentRequestBody Body;
        
        public DeleteAppointmentRequest() {
        }
        
        public DeleteAppointmentRequest(Project_Client1.ServiceReference1.DeleteAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_p;
        
        public DeleteAppointmentRequestBody() {
        }
        
        public DeleteAppointmentRequestBody(string id_p) {
            this.id_p = id_p;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.DeleteAppointmentResponseBody Body;
        
        public DeleteAppointmentResponse() {
        }
        
        public DeleteAppointmentResponse(Project_Client1.ServiceReference1.DeleteAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteAppointmentResponseBody {
        
        public DeleteAppointmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeAppointment", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.ChangeAppointmentRequestBody Body;
        
        public ChangeAppointmentRequest() {
        }
        
        public ChangeAppointmentRequest(Project_Client1.ServiceReference1.ChangeAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_a;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hour;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string instructor;
        
        public ChangeAppointmentRequestBody() {
        }
        
        public ChangeAppointmentRequestBody(int id_a, string date, string hour, string instructor) {
            this.id_a = id_a;
            this.date = date;
            this.hour = hour;
            this.instructor = instructor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.ChangeAppointmentResponseBody Body;
        
        public ChangeAppointmentResponse() {
        }
        
        public ChangeAppointmentResponse(Project_Client1.ServiceReference1.ChangeAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangeAppointmentResponseBody {
        
        public ChangeAppointmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePersonalDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePersonalData", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.ChangePersonalDataRequestBody Body;
        
        public ChangePersonalDataRequest() {
        }
        
        public ChangePersonalDataRequest(Project_Client1.ServiceReference1.ChangePersonalDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePersonalDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phoneNo;
        
        public ChangePersonalDataRequestBody() {
        }
        
        public ChangePersonalDataRequestBody(string cnp, string name, string surname, string age, string phoneNo) {
            this.cnp = cnp;
            this.name = name;
            this.surname = surname;
            this.age = age;
            this.phoneNo = phoneNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePersonalDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePersonalDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.ChangePersonalDataResponseBody Body;
        
        public ChangePersonalDataResponse() {
        }
        
        public ChangePersonalDataResponse(Project_Client1.ServiceReference1.ChangePersonalDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangePersonalDataResponseBody {
        
        public ChangePersonalDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeReviewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeReview", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.ChangeReviewRequestBody Body;
        
        public ChangeReviewRequest() {
        }
        
        public ChangeReviewRequest(Project_Client1.ServiceReference1.ChangeReviewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeReviewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_r;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char stars;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        public ChangeReviewRequestBody() {
        }
        
        public ChangeReviewRequestBody(int id_r, int id_a, char stars, string description) {
            this.id_r = id_r;
            this.id_a = id_a;
            this.stars = stars;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeReviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeReviewResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project_Client1.ServiceReference1.ChangeReviewResponseBody Body;
        
        public ChangeReviewResponse() {
        }
        
        public ChangeReviewResponse(Project_Client1.ServiceReference1.ChangeReviewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangeReviewResponseBody {
        
        public ChangeReviewResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Project_Client1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Project_Client1.ServiceReference1.WebService1Soap>, Project_Client1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.AddPersonalDataResponse Project_Client1.ServiceReference1.WebService1Soap.AddPersonalData(Project_Client1.ServiceReference1.AddPersonalDataRequest request) {
            return base.Channel.AddPersonalData(request);
        }
        
        public void AddPersonalData(string cnp, string name, string surname, string age, string phoneNo) {
            Project_Client1.ServiceReference1.AddPersonalDataRequest inValue = new Project_Client1.ServiceReference1.AddPersonalDataRequest();
            inValue.Body = new Project_Client1.ServiceReference1.AddPersonalDataRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.age = age;
            inValue.Body.phoneNo = phoneNo;
            Project_Client1.ServiceReference1.AddPersonalDataResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).AddPersonalData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddPersonalDataResponse> Project_Client1.ServiceReference1.WebService1Soap.AddPersonalDataAsync(Project_Client1.ServiceReference1.AddPersonalDataRequest request) {
            return base.Channel.AddPersonalDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddPersonalDataResponse> AddPersonalDataAsync(string cnp, string name, string surname, string age, string phoneNo) {
            Project_Client1.ServiceReference1.AddPersonalDataRequest inValue = new Project_Client1.ServiceReference1.AddPersonalDataRequest();
            inValue.Body = new Project_Client1.ServiceReference1.AddPersonalDataRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.age = age;
            inValue.Body.phoneNo = phoneNo;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).AddPersonalDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.AddAppointmentResponse Project_Client1.ServiceReference1.WebService1Soap.AddAppointment(Project_Client1.ServiceReference1.AddAppointmentRequest request) {
            return base.Channel.AddAppointment(request);
        }
        
        public void AddAppointment(int id_a, string cnp, string date, string hour, string instructor) {
            Project_Client1.ServiceReference1.AddAppointmentRequest inValue = new Project_Client1.ServiceReference1.AddAppointmentRequest();
            inValue.Body = new Project_Client1.ServiceReference1.AddAppointmentRequestBody();
            inValue.Body.id_a = id_a;
            inValue.Body.cnp = cnp;
            inValue.Body.date = date;
            inValue.Body.hour = hour;
            inValue.Body.instructor = instructor;
            Project_Client1.ServiceReference1.AddAppointmentResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).AddAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddAppointmentResponse> Project_Client1.ServiceReference1.WebService1Soap.AddAppointmentAsync(Project_Client1.ServiceReference1.AddAppointmentRequest request) {
            return base.Channel.AddAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddAppointmentResponse> AddAppointmentAsync(int id_a, string cnp, string date, string hour, string instructor) {
            Project_Client1.ServiceReference1.AddAppointmentRequest inValue = new Project_Client1.ServiceReference1.AddAppointmentRequest();
            inValue.Body = new Project_Client1.ServiceReference1.AddAppointmentRequestBody();
            inValue.Body.id_a = id_a;
            inValue.Body.cnp = cnp;
            inValue.Body.date = date;
            inValue.Body.hour = hour;
            inValue.Body.instructor = instructor;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).AddAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.AddReviewsResponse Project_Client1.ServiceReference1.WebService1Soap.AddReviews(Project_Client1.ServiceReference1.AddReviewsRequest request) {
            return base.Channel.AddReviews(request);
        }
        
        public void AddReviews(int id_r, int id_a, char stars, string description) {
            Project_Client1.ServiceReference1.AddReviewsRequest inValue = new Project_Client1.ServiceReference1.AddReviewsRequest();
            inValue.Body = new Project_Client1.ServiceReference1.AddReviewsRequestBody();
            inValue.Body.id_r = id_r;
            inValue.Body.id_a = id_a;
            inValue.Body.stars = stars;
            inValue.Body.description = description;
            Project_Client1.ServiceReference1.AddReviewsResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).AddReviews(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddReviewsResponse> Project_Client1.ServiceReference1.WebService1Soap.AddReviewsAsync(Project_Client1.ServiceReference1.AddReviewsRequest request) {
            return base.Channel.AddReviewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.AddReviewsResponse> AddReviewsAsync(int id_r, int id_a, char stars, string description) {
            Project_Client1.ServiceReference1.AddReviewsRequest inValue = new Project_Client1.ServiceReference1.AddReviewsRequest();
            inValue.Body = new Project_Client1.ServiceReference1.AddReviewsRequestBody();
            inValue.Body.id_r = id_r;
            inValue.Body.id_a = id_a;
            inValue.Body.stars = stars;
            inValue.Body.description = description;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).AddReviewsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.DeletePersonalDataResponse Project_Client1.ServiceReference1.WebService1Soap.DeletePersonalData(Project_Client1.ServiceReference1.DeletePersonalDataRequest request) {
            return base.Channel.DeletePersonalData(request);
        }
        
        public void DeletePersonalData(string cnp) {
            Project_Client1.ServiceReference1.DeletePersonalDataRequest inValue = new Project_Client1.ServiceReference1.DeletePersonalDataRequest();
            inValue.Body = new Project_Client1.ServiceReference1.DeletePersonalDataRequestBody();
            inValue.Body.cnp = cnp;
            Project_Client1.ServiceReference1.DeletePersonalDataResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).DeletePersonalData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.DeletePersonalDataResponse> Project_Client1.ServiceReference1.WebService1Soap.DeletePersonalDataAsync(Project_Client1.ServiceReference1.DeletePersonalDataRequest request) {
            return base.Channel.DeletePersonalDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.DeletePersonalDataResponse> DeletePersonalDataAsync(string cnp) {
            Project_Client1.ServiceReference1.DeletePersonalDataRequest inValue = new Project_Client1.ServiceReference1.DeletePersonalDataRequest();
            inValue.Body = new Project_Client1.ServiceReference1.DeletePersonalDataRequestBody();
            inValue.Body.cnp = cnp;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).DeletePersonalDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.DeleteAppointmentResponse Project_Client1.ServiceReference1.WebService1Soap.DeleteAppointment(Project_Client1.ServiceReference1.DeleteAppointmentRequest request) {
            return base.Channel.DeleteAppointment(request);
        }
        
        public void DeleteAppointment(string id_p) {
            Project_Client1.ServiceReference1.DeleteAppointmentRequest inValue = new Project_Client1.ServiceReference1.DeleteAppointmentRequest();
            inValue.Body = new Project_Client1.ServiceReference1.DeleteAppointmentRequestBody();
            inValue.Body.id_p = id_p;
            Project_Client1.ServiceReference1.DeleteAppointmentResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).DeleteAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.DeleteAppointmentResponse> Project_Client1.ServiceReference1.WebService1Soap.DeleteAppointmentAsync(Project_Client1.ServiceReference1.DeleteAppointmentRequest request) {
            return base.Channel.DeleteAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.DeleteAppointmentResponse> DeleteAppointmentAsync(string id_p) {
            Project_Client1.ServiceReference1.DeleteAppointmentRequest inValue = new Project_Client1.ServiceReference1.DeleteAppointmentRequest();
            inValue.Body = new Project_Client1.ServiceReference1.DeleteAppointmentRequestBody();
            inValue.Body.id_p = id_p;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).DeleteAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.ChangeAppointmentResponse Project_Client1.ServiceReference1.WebService1Soap.ChangeAppointment(Project_Client1.ServiceReference1.ChangeAppointmentRequest request) {
            return base.Channel.ChangeAppointment(request);
        }
        
        public void ChangeAppointment(int id_a, string date, string hour, string instructor) {
            Project_Client1.ServiceReference1.ChangeAppointmentRequest inValue = new Project_Client1.ServiceReference1.ChangeAppointmentRequest();
            inValue.Body = new Project_Client1.ServiceReference1.ChangeAppointmentRequestBody();
            inValue.Body.id_a = id_a;
            inValue.Body.date = date;
            inValue.Body.hour = hour;
            inValue.Body.instructor = instructor;
            Project_Client1.ServiceReference1.ChangeAppointmentResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).ChangeAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangeAppointmentResponse> Project_Client1.ServiceReference1.WebService1Soap.ChangeAppointmentAsync(Project_Client1.ServiceReference1.ChangeAppointmentRequest request) {
            return base.Channel.ChangeAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangeAppointmentResponse> ChangeAppointmentAsync(int id_a, string date, string hour, string instructor) {
            Project_Client1.ServiceReference1.ChangeAppointmentRequest inValue = new Project_Client1.ServiceReference1.ChangeAppointmentRequest();
            inValue.Body = new Project_Client1.ServiceReference1.ChangeAppointmentRequestBody();
            inValue.Body.id_a = id_a;
            inValue.Body.date = date;
            inValue.Body.hour = hour;
            inValue.Body.instructor = instructor;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).ChangeAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.ChangePersonalDataResponse Project_Client1.ServiceReference1.WebService1Soap.ChangePersonalData(Project_Client1.ServiceReference1.ChangePersonalDataRequest request) {
            return base.Channel.ChangePersonalData(request);
        }
        
        public void ChangePersonalData(string cnp, string name, string surname, string age, string phoneNo) {
            Project_Client1.ServiceReference1.ChangePersonalDataRequest inValue = new Project_Client1.ServiceReference1.ChangePersonalDataRequest();
            inValue.Body = new Project_Client1.ServiceReference1.ChangePersonalDataRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.age = age;
            inValue.Body.phoneNo = phoneNo;
            Project_Client1.ServiceReference1.ChangePersonalDataResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).ChangePersonalData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangePersonalDataResponse> Project_Client1.ServiceReference1.WebService1Soap.ChangePersonalDataAsync(Project_Client1.ServiceReference1.ChangePersonalDataRequest request) {
            return base.Channel.ChangePersonalDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangePersonalDataResponse> ChangePersonalDataAsync(string cnp, string name, string surname, string age, string phoneNo) {
            Project_Client1.ServiceReference1.ChangePersonalDataRequest inValue = new Project_Client1.ServiceReference1.ChangePersonalDataRequest();
            inValue.Body = new Project_Client1.ServiceReference1.ChangePersonalDataRequestBody();
            inValue.Body.cnp = cnp;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.age = age;
            inValue.Body.phoneNo = phoneNo;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).ChangePersonalDataAsync(inValue);
        }
        
        public void DeleteReview(int id_r) {
            base.Channel.DeleteReview(id_r);
        }
        
        public System.Threading.Tasks.Task DeleteReviewAsync(int id_r) {
            return base.Channel.DeleteReviewAsync(id_r);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project_Client1.ServiceReference1.ChangeReviewResponse Project_Client1.ServiceReference1.WebService1Soap.ChangeReview(Project_Client1.ServiceReference1.ChangeReviewRequest request) {
            return base.Channel.ChangeReview(request);
        }
        
        public void ChangeReview(int id_r, int id_a, char stars, string description) {
            Project_Client1.ServiceReference1.ChangeReviewRequest inValue = new Project_Client1.ServiceReference1.ChangeReviewRequest();
            inValue.Body = new Project_Client1.ServiceReference1.ChangeReviewRequestBody();
            inValue.Body.id_r = id_r;
            inValue.Body.id_a = id_a;
            inValue.Body.stars = stars;
            inValue.Body.description = description;
            Project_Client1.ServiceReference1.ChangeReviewResponse retVal = ((Project_Client1.ServiceReference1.WebService1Soap)(this)).ChangeReview(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangeReviewResponse> Project_Client1.ServiceReference1.WebService1Soap.ChangeReviewAsync(Project_Client1.ServiceReference1.ChangeReviewRequest request) {
            return base.Channel.ChangeReviewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project_Client1.ServiceReference1.ChangeReviewResponse> ChangeReviewAsync(int id_r, int id_a, char stars, string description) {
            Project_Client1.ServiceReference1.ChangeReviewRequest inValue = new Project_Client1.ServiceReference1.ChangeReviewRequest();
            inValue.Body = new Project_Client1.ServiceReference1.ChangeReviewRequestBody();
            inValue.Body.id_r = id_r;
            inValue.Body.id_a = id_a;
            inValue.Body.stars = stars;
            inValue.Body.description = description;
            return ((Project_Client1.ServiceReference1.WebService1Soap)(this)).ChangeReviewAsync(inValue);
        }
    }
}
